// CATEGORIES ROUTE 
// Get all categories
GET https://joke-api-hoang-jevgeni.herokuapp.com/categories

###
// Get all jokes from a category
GET https://joke-api-hoang-jevgeni.herokuapp.com/categories/Bike

###
// Get a random joke from a category
GET https://joke-api-hoang-jevgeni.herokuapp.com/categories/Rocket/random

###
// Create a new category
POST https://joke-api-hoang-jevgeni.herokuapp.com/categories
Content-Type: application/json

{
    "name": "Bike"
}

###
// Create a new joke in a category
POST https://joke-api-hoang-jevgeni.herokuapp.com/categories/Bike
Content-Type: application/json

{
    "name": "bike joke",
    "content": "This is the first joke about bike and train"
}

###
// Add an existing joke to a category by joke id
PATCH  https://joke-api-hoang-jevgeni.herokuapp.com/categories/Train/61644d93dee4cbf967703992





// JOKES ROUTE
###
// Get all jokes
GET https://joke-api-hoang-jevgeni.herokuapp.com/jokes

###
// Get a joke by its id
GET https://joke-api-hoang-jevgeni.herokuapp.com/jokes/6161afdd59c4ae7603246a92

###
// Get a random joke from all jokes
GET https://joke-api-hoang-jevgeni.herokuapp.com/jokes/random

###
// Give a joke a like or dislike
PATCH  https://joke-api-hoang-jevgeni.herokuapp.com/jokes/61644d93dee4cbf967703992/favor/dislike


###
// Delete all jokes
DELETE  https://joke-api-hoang-jevgeni.herokuapp.com/jokes
