// CATEGORIES ROUTE 
// Get all categories
GET http://localhost:8000/categories

###
// Get all jokes from a category
GET http://localhost:8000/categories/Bike

###
// Get a random joke from a category
GET http://localhost:8000/categories/Rocket/random

###
// Create a new category
POST http://localhost:8000/categories
Content-Type: application/json

{
    "name": "Bike"
}

###
// Create a new joke in a category
POST http://localhost:8000/categories/Bike
Content-Type: application/json

{
    "name": "bike joke",
    "content": "This is the first joke about bike and train"
}

###
// Add an existing joke to a category by joke id
PATCH  http://localhost:8000/categories/Train/61644d93dee4cbf967703992





// JOKES ROUTE
###
// Get all jokes
GET http://localhost:8000/jokes

###
// Get a joke by its id
GET http://localhost:8000/jokes/6161afdd59c4ae7603246a92

###
// Get a random joke from all jokes
GET http://localhost:8000/jokes/random

###
// Give a joke a like or dislike
PATCH  http://localhost:8000/jokes/61644d93dee4cbf967703992/favor/dislike


###
// Delete all jokes
DELETE  http://localhost:8000/jokes
